import type { Metadata } from "next";
import { Inter } from "next/font/google";

import { Toaster } from "@/components/ui/toaster";
import Navbar from "@/components/ui/Navbar";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="flex flex-col w-full justify-evenly h-full">
      <Toaster />
      <div className="w-full flex-none ">
        <Navbar />
      </div>
      <div className="p-6 w-full">{children}</div>
    </div>
  );
}
